apiVersion: apps/v1
kind: Deployment
metadata:
  name: practicecheckconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Practicecheckconfig
  template:
    metadata:
      labels:
        app: Practicecheckconfig
    spec:
      containers:
      - name: practicecheckrepos
        image: dnazureacr.azurecr.io/practicecheckrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: practicecheckconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Practicecheckconfig